nacos:
  addr: 172.16.25.155:8848,172.16.25.155:8849,172.16.25.155:8850
  namespace: hutu
spring:
  cloud:
    nacos:
      password: nacos
      username: nacos
      config:
        file-extension: yml
        namespace: ${nacos.namespace}
        server-addr: ${nacos.addr}
      discovery:
        namespace: ${nacos.namespace}
        server-addr: ${nacos.addr}
  config:
    import:
      - optional:nacos:common.yml  # 监听 DEFAULT_GROUP:test.yml
#      - optional:nacos:test01.yml?group=group_01 # 覆盖默认 group，监听 group_01:test01.yml
#      - optional:nacos:test02.yml?group=group_02&refreshEnabled=false # 不开启动态刷新
#      - nacos:test03.yml # 在拉取nacos配置异常时会快速失败，会导致 spring 容器启动失败