server:
  port: 8761
spring:
  application:
    name: hutu-gateway
  jmx:
    enabled: false
  cloud:
    gateway:
      # 跨域配置
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
      default-filters:
#      - PrefixPath=/httpbin
      - AddResponseHeader=X-Response-Default-Foo, Default-Bar
#      routes:
#      - id: hutu-auth
#        uri: http://localhost:8762
#        predicates:
#        - Path=/auth/**
#        filters:
#        - StripPrefix=1
#
#      - id: hutu-upms
#        uri: http://localhost:8765
#        predicates:
#        - Path=/upms/**
#        filters:
#        - StripPrefix=1

    nacos:
      discovery:
        serverAddr: 127.0.0.1:8848
      dataId: gateway
      group: DEFAULT_GROUP

# 阿里云AHAS在线高可用服务
#ahas:
#  namespace: default
#  license: a9dc8a65ae5f4fbfa99bc3fe9c13cadb
#project:
#      name: AppName

# 聚合文档配置
hutu:
  document:
    resources:
      - name: 用户系统
        location: /a
      - name: 权限系统
        location: /b