server:
  port: 8761
spring:
  application:
    name: hutu-gateway
  jmx:
    enabled: false
  cloud:
    gateway:
      default-filters:
#      - PrefixPath=/httpbin
      - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      routes:
      - id: hutu-auth
        uri: http://localhost:8762
        predicates:
        - Path=/auth/**
        filters:
        - StripPrefix=1

      - id: hutu-upms
        uri: http://localhost:8765
        predicates:
        - Path=/upms1/**
        filters:
        - StripPrefix=1
        - name: RequestRateLimiter
          args:
            keyResolver: '#{@ipAddressKeyResolver}'
            in-memory-rate-limiter:
              replenish-rate: 1
              burst-capacity: 2
    nacos:
      discovery:
        serverAddr: 127.0.0.1:8848
      dataId: gateway
      group: test
