spring:
  application:
    name: hutu-gateway
  jmx:
    enabled: false
  cloud:
    gateway:
      default-filters:
#      - PrefixPath=/httpbin
      - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      routes:
      - id: host_route
        uri: http://localhost:8764
        predicates:
        - Path=/a/**
        filters:
        - StripPrefix=1

      - id: host_route
        uri: http://localhost:8765
        predicates:
        - Path=/b/**
        filters:
        - StripPrefix=1
        - name: RequestRateLimiter
          args:
            keyResolver: '#{@ipAddressKeyResolver}'
            in-memory-rate-limiter:
              replenish-rate: 1
              burst-capacity: 2
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8762