spring:
  datasource:
    url: jdbc:mysql://${hutu.datasource.ip}:3306/greentree?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ${hutu.datasource.username}
    password: ${hutu.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hutu.upms.admin.entity
  global-config:
    db-config:
      id-type: auto

#swagger配置参考： https://github.com/SpringForAll/spring-boot-starter-swagger
swagger:
  enabled: true
  title: 管理系统api文档
  version: 1.0.0
  base-package: com.hutu.upms
  base-path: /**
  exclude-path: /error, /ops/**
